name: matchify
description: The football manager application
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter_switch: ^0.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  image_picker: ^1.0.4
  quickalert: ^1.0.2
  numberpicker: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true   
  assets:     
    - assets/images/edit.png
    - assets/images/plus.png
    - assets/images/messi.png
    - assets/images/trash.png
    - assets/images/done.png
    - assets/images/minus.png
    - assets/images/play.png
    - assets/images/ball.png
    - assets/images/red_card.png
    - assets/images/yellow_card.png
    - assets/images/blue_color.png
    - assets/images/red_color.png
